name: PR Check

on:
  pull_request:

jobs:
  clang-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting in /src
        run: |
          find ./src \( -iname '*.h' -o -iname '*.cpp' \) -print0 | xargs -0 clang-format --dry-run --Werror

  micro-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x microbuild.sh microinstall.sh microinit.sh

      - name: Run microinstall
        run: sh microinstall.sh

      - name: Run microinit
        run: sh microinit.sh src

      - name: Run aliases.sh
        run: sh microbuild.sh BUILD_DIRECTORY=./src